version: "3.7"
services:
    php-base:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./php/base
        image: php-base
        container_name: php-base
        restart: unless-stopped
        volumes:
            - ../docker/php:/usr/local/etc/php/conf.d/
            - ../:/var/www
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    mysql:
        image: mysql:8.0
        container_name: mysql
#        platform: linux/x86_64
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: shop
            MYSQL_ROOT_PASSWORD: root
            DB_USER: root
            DB_PASSWORD: root
            SERVICE_NAME: mysql
        volumes:
            - ../structure/mysql/data:/var/lib/mysql
#            - ../structure/mysql/my_dev.cnf:/etc/my.cnf.d/my.cnf
        networks:
            - laravel
        depends_on:
            - php-base

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php-base
        environment:
            - NGINX_PORT=8080
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www
            - ./nginx/config/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    node:
        container_name: node
        image: "node:14"
        restart: unless-stopped
        user: "node"
        working_dir: /var/www/nextjs
        tty: true
        ports:
            - "80:3000"
        volumes:
            - ../:/var/www/

networks:
    laravel:
