version: "3.7"
services:
    php-app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./php/base
        image: php-app
        container_name: php-app
        restart: unless-stopped
        volumes:
            - ../docker/php:/usr/local/etc/php/conf.d/
            - ../:/var/www
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    postgres:
      image: postgres:15
      container_name: postgres
      restart: always
      shm_size: '1gb'
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: prof_list
      volumes:
        - ../structure/postgres/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - laravel
      depends_on:
        - php-app

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php-app
        environment:
            - NGINX_PORT=8080
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www
            - ./nginx/config/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    node:
        container_name: node
        image: "node:14"
        restart: unless-stopped
        user: "node"
        working_dir: /var/www/nextjs
        tty: true
        ports:
            - "80:3000"
        volumes:
            - ../:/var/www/

networks:
    laravel:
