version: "3.7"
services:
    php-app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./php/base
        image: php-app
        container_name: php-app
        restart: unless-stopped
        volumes:
            - ../docker/php:/usr/local/etc/php/conf.d/
            - ../:/var/www
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    postgres:
      image: postgres:15
      container_name: postgres
      restart: always
      shm_size: '1gb'
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: prof_list
      volumes:
        - ../structure/postgres/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - laravel
      depends_on:
        - php-app

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www
            - ./nginx/nginx_dev.conf:/etc/nginx/nginx_dev.conf:ro
            - ./nginx/nginx_prod.conf:/etc/nginx/nginx_prod.conf:ro
            - ./nginx/cert.pem:/etc/cert.pem
            - ./nginx/key.pem:/etc/key.pem
        networks:
            - laravel
        environment:
          - APP_ENV=${APP_ENV:-dev}
        command: /bin/sh -c "envsubst '$$APP_ENV' < /etc/nginx/nginx_$$APP_ENV.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

    node:
        container_name: node
        image: "node:18"
        restart: unless-stopped
        user: "node"
        working_dir: /var/www/nextjs
        tty: true
        ports:
            - "3000:3000"
        networks:
          - laravel
        volumes:
            - ../:/var/www/
#    certbot:
#      ports:
#        - "6000:80"
#      volumes:
#        - ./nginx/:/etc/nginx/
#      build:
#        context: ./certbot
#        dockerfile: Dockerfile
#        args:
#          DOMAIN_EMAIL: 'proflist43@yandex.ru'
#          DOMAIN_URL: 'kirovprofnastil.ru'

networks:
    laravel:
